import type { Combatant } from "@/lib/types/combat";

export const SAMPLE_ENCOUNTER: Omit<Combatant, "id">[] = [
  {
    name: "Goblin 1",
    current_hp: 7,
    max_hp: 7,
    temp_hp: 0,
    ac: 15,
    spell_save_dc: null,
    initiative: null,
    initiative_order: null,
    conditions: [],
    ruleset_version: "2014",
    is_defeated: false,
    is_player: false,
    monster_id: null,
    token_url: null,
    creature_type: null,
    display_name: null,
    monster_group_id: null,
    group_order: null,
    dm_notes: "",
    player_notes: "Exemplo — edite ou remova à vontade",
  },
  {
    name: "Goblin 2",
    current_hp: 7,
    max_hp: 7,
    temp_hp: 0,
    ac: 15,
    spell_save_dc: null,
    initiative: null,
    initiative_order: null,
    conditions: [],
    ruleset_version: "2014",
    is_defeated: false,
    is_player: false,
    monster_id: null,
    token_url: null,
    creature_type: null,
    display_name: null,
    monster_group_id: null,
    group_order: null,
    dm_notes: "",
    player_notes: "Exemplo — edite ou remova à vontade",
  },
  {
    name: "Goblin 3",
    current_hp: 7,
    max_hp: 7,
    temp_hp: 0,
    ac: 15,
    spell_save_dc: null,
    initiative: null,
    initiative_order: null,
    conditions: [],
    ruleset_version: "2014",
    is_defeated: false,
    is_player: false,
    monster_id: null,
    token_url: null,
    creature_type: null,
    display_name: null,
    monster_group_id: null,
    group_order: null,
    dm_notes: "",
    player_notes: "Exemplo — edite ou remova à vontade",
  },
  {
    name: "Herói 1",
    current_hp: 12,
    max_hp: 12,
    temp_hp: 0,
    ac: 14,
    spell_save_dc: null,
    initiative: null,
    initiative_order: null,
    conditions: [],
    ruleset_version: null,
    is_defeated: false,
    is_player: true,
    monster_id: null,
    token_url: null,
    creature_type: null,
    display_name: null,
    monster_group_id: null,
    group_order: null,
    dm_notes: "",
    player_notes: "",
  },
  {
    name: "Herói 2",
    current_hp: 12,
    max_hp: 12,
    temp_hp: 0,
    ac: 14,
    spell_save_dc: null,
    initiative: null,
    initiative_order: null,
    conditions: [],
    ruleset_version: null,
    is_defeated: false,
    is_player: true,
    monster_id: null,
    token_url: null,
    creature_type: null,
    display_name: null,
    monster_group_id: null,
    group_order: null,
    dm_notes: "",
    player_notes: "",
  },
];
