import { randomBytes } from "node:crypto";
import { JOIN_CODE_RE } from "./join-code";

describe("JOIN_CODE_RE charset invariant", () => {
  it("accepts every hex-uppercase char individually in each of the 8 positions", () => {
    const hexChars = "0123456789ABCDEF";
    for (const ch of hexChars) {
      const code = ch.repeat(8);
      expect(JOIN_CODE_RE.test(code)).toBe(true);
    }
  });

  it("accepts 1000 codes generated by the same algorithm as the SQL function", () => {
    // Mirrors `upper(substr(md5(random()::text), 1, 8))` in
    // supabase/migrations/122_create_campaign_atomic.sql: 8 uppercase hex
    // chars. If this loop ever fails, the regex has drifted from the
    // generator and every new code rejects the accept flow in production.
    for (let i = 0; i < 1000; i++) {
      const code = randomBytes(4).toString("hex").toUpperCase();
      expect(JOIN_CODE_RE.test(code)).toBe(true);
    }
  });

  it("rejects codes outside the charset or length contract", () => {
    const invalid = [
      "",
      "ABCDEFG",
      "ABCDEFGH1",
      "ABCDEFGZ",
      "ABCDEF GH",
      "ABCDEF-1",
      "GGGGGGGG",
      "1234567",
      "123456789",
    ];
    for (const code of invalid) {
      expect(JOIN_CODE_RE.test(code)).toBe(false);
    }
  });

  it("accepts lowercase variants (defensive — server emits uppercase but users paste freely)", () => {
    expect(JOIN_CODE_RE.test("abcdef01")).toBe(true);
    expect(JOIN_CODE_RE.test("AbCdEf01")).toBe(true);
  });
});
