/**
 * Join-code charset contract.
 *
 * The server generates 8-char join codes from uppercase md5 hex:
 *   `upper(substr(md5(random()::text), 1, 8))`
 * in `create_campaign_with_settings` (supabase/migrations/122_create_campaign_atomic.sql).
 * md5 hex emits `[0-9a-f]`, uppercased to `[0-9A-F]`.
 *
 * This module is the **single source of truth** for the client-side validator.
 * Any change to the SQL generator's charset MUST be mirrored here (and vice
 * versa) — drift will silently reject ~every generated code. A prior drift
 * (`[A-Z2-9]{8}` vs. `[0-9A-F]{8}`) rejected every code containing `0` or `1`,
 * which was the entire accept flow in production until commit 7afd9a37 on
 * 2026-04-21. See docs/bugfix-join-code-validator-drift-2026-04-21.md.
 *
 * Enforced by `lib/validation/join-code.test.ts` — the test samples 1000
 * codes generated by the same algorithm as the SQL function and asserts the
 * regex accepts them all.
 */
export const JOIN_CODE_RE = /^[0-9A-F]{8}$/i;
