#!/usr/bin/env tsx
/**
 * Verify byte-level parity between blog post sources and baseline.
 *
 * Usage:
 *   rtk npx tsx scripts/verify-blog-parity.ts              # compares against baseline
 *   rtk npx tsx scripts/verify-blog-parity.ts --snapshot   # writes new baseline from current sources
 *
 * Reads components/blog/posts/post-NN-*.tsx, extracts each default-exported
 * BlogPostN function body, hashes it, and compares against
 * .tmp/blog-parity.json (generated by scripts/split-blog-monolith.ts or the
 * `--snapshot` flag of this script).
 *
 * Exit 1 on mismatch.
 */

import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const POSTS_DIR = join(ROOT, "components/blog/posts");
const MANIFEST = join(ROOT, ".tmp/blog-parity.json");
const TMP_DIR = join(ROOT, ".tmp");

const SNAPSHOT = process.argv.includes("--snapshot");

interface ManifestEntry {
  n: number;
  slug: string;
  hash: string;
}
interface Manifest {
  generatedAt: string;
  source: string;
  posts: ManifestEntry[];
  sharedHash?: string;
}

function sha256(s: string): string {
  return createHash("sha256").update(s).digest("hex");
}

function findMatchingBrace(source: string, openBraceIdx: number): number {
  let depth = 0;
  let inString: string | null = null;
  let inTemplate = false;
  let inLineComment = false;
  let inBlockComment = false;
  let i = openBraceIdx;
  for (; i < source.length; i++) {
    const ch = source[i];
    const next = source[i + 1];
    if (inLineComment) {
      if (ch === "\n") inLineComment = false;
      continue;
    }
    if (inBlockComment) {
      if (ch === "*" && next === "/") {
        inBlockComment = false;
        i++;
      }
      continue;
    }
    if (inString) {
      if (ch === "\\") {
        i++;
        continue;
      }
      if (ch === inString) inString = null;
      continue;
    }
    if (inTemplate) {
      if (ch === "\\") {
        i++;
        continue;
      }
      if (ch === "`") inTemplate = false;
      continue;
    }
    if (ch === "/" && next === "/") {
      inLineComment = true;
      i++;
      continue;
    }
    if (ch === "/" && next === "*") {
      inBlockComment = true;
      i++;
      continue;
    }
    if (ch === '"' || ch === "'") {
      inString = ch;
      continue;
    }
    if (ch === "`") {
      inTemplate = true;
      continue;
    }
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) return i;
    }
  }
  throw new Error(`No matching brace from ${openBraceIdx}`);
}

function extractBody(filepath: string): { n: number; body: string } {
  const src = readFileSync(filepath, "utf8");
  const m = src.match(/export default function BlogPost(\d+)\(\)\s*\{/);
  if (!m || m.index === undefined) {
    throw new Error(`No BlogPostN export in ${filepath}`);
  }
  const n = Number.parseInt(m[1], 10);
  const openBrace = src.indexOf("{", m.index);
  const closeBrace = findMatchingBrace(src, openBrace);
  return { n, body: src.slice(openBrace + 1, closeBrace) };
}

const files = readdirSync(POSTS_DIR)
  .filter((f) => f.startsWith("post-") && f.endsWith(".tsx"))
  .sort();

if (files.length === 0) {
  console.error("✗ No post-*.tsx files found in components/blog/posts/");
  process.exit(1);
}

const current: ManifestEntry[] = files.map((f) => {
  const { n, body } = extractBody(join(POSTS_DIR, f));
  const slug = f.replace(/^post-\d+-/, "").replace(/\.tsx$/, "");
  return { n, slug, hash: sha256(body) };
});
current.sort((a, b) => a.n - b.n);

// Also hash _shared.tsx — catches changes to imports/helpers that could alter
// rendered HTML even when post bodies are byte-equivalent.
const sharedPath = join(POSTS_DIR, "_shared.tsx");
const currentSharedHash = existsSync(sharedPath)
  ? sha256(readFileSync(sharedPath, "utf8"))
  : null;

if (SNAPSHOT) {
  if (!existsSync(TMP_DIR)) mkdirSync(TMP_DIR, { recursive: true });
  const manifest: Manifest = {
    generatedAt: new Date().toISOString(),
    source: POSTS_DIR,
    posts: current,
    sharedHash: currentSharedHash ?? undefined,
  };
  writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2));
  console.log(
    `✓ Snapshot written to ${MANIFEST} (${current.length} posts${currentSharedHash ? " + _shared.tsx" : ""})`,
  );
  process.exit(0);
}

if (!existsSync(MANIFEST)) {
  console.error(
    `✗ ${MANIFEST} missing. Run with --snapshot first, or run ` +
      `scripts/split-blog-monolith.ts to generate one.`,
  );
  process.exit(1);
}

const manifest: Manifest = JSON.parse(readFileSync(MANIFEST, "utf8"));
const baseline = new Map(manifest.posts.map((p) => [p.n, p]));

let mismatches = 0;
for (const c of current) {
  const base = baseline.get(c.n);
  if (!base) {
    console.error(`✗ BlogPost${c.n} (${c.slug}) not in baseline manifest`);
    mismatches++;
    continue;
  }
  if (base.hash !== c.hash) {
    console.error(
      `✗ BlogPost${c.n} (${c.slug}) body hash mismatch\n` +
        `    baseline: ${base.hash}\n` +
        `    current:  ${c.hash}`,
    );
    mismatches++;
  }
}

for (const [n, entry] of baseline) {
  if (!current.find((c) => c.n === n)) {
    console.error(`✗ BlogPost${n} (${entry.slug}) missing from current sources`);
    mismatches++;
  }
}

if (manifest.sharedHash && currentSharedHash && manifest.sharedHash !== currentSharedHash) {
  console.error(
    `✗ _shared.tsx hash mismatch\n` +
      `    baseline: ${manifest.sharedHash}\n` +
      `    current:  ${currentSharedHash}`,
  );
  mismatches++;
}

if (mismatches === 0) {
  console.log(
    `✓ Parity OK — ${current.length} posts match baseline ` +
      `(generated ${manifest.generatedAt})`,
  );
  process.exit(0);
}

console.error(`✗ ${mismatches} parity violation(s)`);
process.exit(1);
